### ISSUE TITLE
ask Michelle to add the data files in csv format

### ISSUE THREAD

**Issue by jhpoelen** [GoMexSI/abascal#1]
If you need help, please ask Theresa @tmitchell1 .

**Comment by jhpoelen** [comment]
For Michelle - 

1. create a github account 
2. share github user name in this issue 
3. @jhpoelen to add Michelle to the contributors of this repository. 
4. Michelle able to add the csv files

**Comment by iabascal** [comment]
@jhpoelen my username is: iabascal

**Comment by jhpoelen** [comment]
I've added you as an "admin" to the repository. Please confirm that you accepted the invitation.

**Comment by jhpoelen** [comment]
Thanks for adding the csv files!
